### ISSUE TITLE
The shaded API is complaining for no reason

### ISSUE THREAD

**Issue by DavidTheExplorer** [tr7zw/Item-NBT-API#241]
This is what I get in my console:
![image](https://github.com/tr7zw/Item-NBT-API/assets/69223217/904c3716-a3cf-47a9-84b7-3dfc147821d5)

Which makes zero sense, given the fact that I do the shading correctly:
![image](https://github.com/tr7zw/Item-NBT-API/assets/69223217/c1216d77-68ff-425f-a013-7d2c67c12b57)
My _shade.base_ reference is irrelevant, but I promise it's not empty lol

**Comment by tr7zw** [comment]
You are shading the incorrect dependency, thats why you are also using the wrong shade pattern. Remove the -plugin from the dependency and then fix the pattern. https://github.com/tr7zw/Item-NBT-API/wiki/Using-Maven#option-2-shading-the-nbt-api-into-your-plugin

**Comment by Ryhon0** [comment]
Same issue here
```xml
<relocation>
  <pattern>de.tr7zw</pattern>
  <shadedPattern>link.ryhn.markdownchat.nbtapi</shadedPattern>
</relocation>
```
The linked example doesn't do anything because there is no `de.tr7zw.changeme.nbtapi`. My config moves `de.tr7zw.nbtapi` and  `de.tr7zw.nbtinjector` to `link.ryhn.markdownchat.nbtapi`
![image](https://github.com/tr7zw/Item-NBT-API/assets/21126698/fb9983a9-43b1-45e2-9485-d2f046a4374f)
![image](https://github.com/tr7zw/Item-NBT-API/assets/21126698/78e32f5b-c29a-4273-a078-88dfb745c3a1)
It should be all good but it still nags me about relocating,
