### ISSUE TITLE
NoSuchFieldError MC_1_13_R1 Disabling Plugin

### ISSUE THREAD

**Issue by CarrlosM** [tr7zw/Item-NBT-API#36]
I'm unable to use this plugin on my server. It throws an error on startup and disables.

Tried on latest, 1.8.2, and 1.7-Snapshot, same results

Startup log - https://pastebin.com/A5qYvaVC

**Comment by tr7zw** [comment]
That happens if one of your used plugins has the nbt-api shaded into it without changing the packet used. Then the newer version and old version overwrite each other and in this case the versions enum became an old one. For future versions I may force people to change the package to stop this from happening, right now check the other plugin jars for de.tr7zw.itemnbtapi and contact the plugin author to update it to a newer version.

**Comment by CarrlosM** [comment]
Resolved, it was an issue with [Vouchers](https://www.spigotmc.org/resources/vouchers.13654/)
