### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by SlimeDog** [tr7zw/Item-NBT-API#78]
Spigot 1.15.2
NBTAPI 2.3.1

- Naming consistency
  - Downloaded file: **item-nbt-api-plugin-2.3.1.jar** should be **NBTAPI-2.3.1.jar** to be consistent with
  - **name: NBTAPI** in plugin.yml
  - Directory (with no content): plugins/NBTAPI/

- Configuration
  - Implement control of update checking in config.yml. We have an automagical update-checker, and do not want individual plugins to do so. Others do, of course, so it should be an options, default true.

- Messages
```
[17:25:55] [Server thread/INFO]: [NBTAPI] All Classes where able to link!
[17:25:55] [Server thread/INFO]: [NBTAPI] Methods:
[17:25:55] [Server thread/INFO]: [NBTAPI] All Methods where able to link!
```
should be
```
[17:25:55] [Server thread/INFO]: [NBTAPI] All Classes were able to link!
[17:25:55] [Server thread/INFO]: [NBTAPI] Methods:
[17:25:55] [Server thread/INFO]: [NBTAPI] All Methods were able to link!
```
(where => were)

**Comment by tr7zw** [comment]
The ``item`` part is historically grown since the original lib was just for items. With version 2.0 I made lots of breaking changes and thats where the name was changed to NBTAPI and the package name was changed, so the 1.x item-nbt-api and 2.x nbt-api won't conflict with each other. Some places had to keep the old name like bStats and maven, so that's why the output jar has the item prefix and that can't be changed anymore without breaking other people's plugins or raising confusion.

Adding a config is definitely something I'll add, for now only other plugins(shaded or not) can disable the update-check/bStats or enable the nbt-injector. It's also noteworthy that the update check is especially useful/needed when people shade the API into their plugin.

Also quickly making a commit to fix the typo 👍

**Comment by tr7zw** [comment]
Moved the config part to #79

**Comment by SlimeDog** [comment]
No worries. I expect to remove NBTAPI as soon as **IllegalStack** figures out the issue that requires it to be installed separately. Perhaps you could help him: see https://www.spigotmc.org/threads/dupe-fixes-illegal-stack-remover.259090/page-52#post-3780533 and several pages previous.
